### PR TITLE
Add additional options in decompress function

### PR DESCRIPTION
**Pull request by fourier**
- Added possibility to specify output buffer and position
  in the input buffer
- Small performance optimizations with additional
  type information
- Minor version bumped since API has been changed

### CODE REVIEW

**Comment by fourier** [comment]
Anyone could comment/accept it?

**Comment by arbv** [comment]
Thank you for the changes! I was unable to work on Corman Lisp for some time. I will try to check and accept them them as soon as I can. I think that having addtional options won't hurt.

BTW, I believe that we should update zlib to the newer version too.

**Comment by arbv** [comment]
Oh, sorry guys. I beleved it was pull request to the Corman Lisp (it has zlib interface). I should not have merged this one,

**Comment by fourier** [comment]
Hm since nobody has responded apart from you apparently nobody cares if it is merged or not :(

**Comment by arbv** [comment]
:) I still believe it is in overall a good change, though.

8 бер. 2017 р. 13:58 "Alexey Veretennikov" <notifications@github.com> пише:

**Comment by luismbo** [comment]
@arbv cool, thanks for taking the time to review it.

**Comment by arbv** [comment]
Thanks, but I did it unintentionally :) Next time I will pay more attention
to the name of the project which I try to maintain.

8 бер. 2017 р. 16:49 "Luís Oliveira" <notifications@github.com> пише:

**Pull request merged**
